---
title: "strings and factors"
author: "Rachel"
date: "10/25/2021"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.colour = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


## Strings and regex 
```{r}
string_vec = c("my", "name", "is", "rachel")

str_detect(string_vec, "rachel")
str_replace(string_vec, "rachel", "Rachel")
```


```{r}
string_vec = c(
  "i think we all rule for participating", 
  "i think I have benn cought", 
  "i think this will be quite fun", 
  "it will be fun, i think"
)

str_detect(string_vec, "i think")
```

```{r}
string_vec = c(
  "i think we all rule for participating", 
  "i think I have benn cought", 
  "i think this will be quite fun", 
  "it will be fun, i think"
)

str_detect(string_vec, "^i think")      
str_detect(string_vec, "i think$")   
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?", 
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "bush")
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?", 
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "Bush")
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?", 
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "[Bb]ush")
```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant slee :('
)

str_detect(string_vec, "[0-9][a-zA-Z]")     
```


```{r}
string_vec = c(
  'Its 7:11 in the evening', 
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
)

str_detect(string_vec, "7.11")
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [5-7]'
)

str_detect(string_vec, "\\[")
```


## Factors 

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

factor_vec
```

## Factors 

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

factor_vec
```


